### ISSUE TITLE
Typo (Shelder -> Shelter)

### ISSUE THREAD

**Issue by veloman-yunkan** [bwr57/CustomizePublicTransportStop#4]
There is a typo in the English text resource. **Shelder** must be changed to **Shelter**.

https://github.com/bwr57/CustomizePublicTransportStop/blob/16dc5c18352127e2e9fbb74f473e1cb8b836b15c/Text/en.txt#L23

**Comment by floscher** [comment]
Everything from this JOSM plugin is now part of the [`pt_assistant` plugin](https://github.com/JOSM/pt_assistant) starting with [release `2.1.10`](https://github.com/JOSM/pt_assistant/releases/tag/v2.1.10). That release also contains a fix for this issue, see commit https://github.com/JOSM/pt_assistant/commit/24bf96ec57bf3e9550771f4bbd9bae6167b399de .

**Comment by bwr57** [comment]
Fixed
