### ISSUE TITLE
NoSuchElementException at CreateStopAreaFromSelectedObjectOperation.performCustomizing

### ISSUE THREAD

**Issue by don-vip** [bwr57/CustomizePublicTransportStop#6]
See bug reports on JOSM bug tracker:
https://josm.openstreetmap.de/ticket/13840
https://josm.openstreetmap.de/ticket/15500

**Comment by floscher** [comment]
Everything from this JOSM plugin is now part of the [`pt_assistant` plugin](https://github.com/JOSM/pt_assistant) starting with [release `2.1.10`](https://github.com/JOSM/pt_assistant/releases/tag/v2.1.10). That release also contains a fix for this issue, see commit https://github.com/JOSM/pt_assistant/commit/af7eabb30f50b115de00fea2187d2b01f7a55579 .

**Comment by bwr57** [comment]
Fixed
